services:
  postgres:
    image: postgres:16
    container_name: lab_postgres
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student_pw
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: lab_metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: analytics
      MB_DB_PORT: 5432
      MB_DB_USER: student
      MB_DB_PASS: student_pw
      MB_DB_HOST: postgres
    depends_on:
      - postgres

volumes:
  pgdata:
  metabase_data: